# Generated by Django 5.0.3 on 2024-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_empleado_emp_area_empleado_emp_auxiliotransporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Emp_subtipoTrabajador',
            field=models.IntegerField(choices=[(0, 'No aplica'), (1, 'Dependiente pensionado por vejez activo')], max_length=106, verbose_name='Subtipo de trabajador'),
        ),
    ]
